title: Hello, I'm Philip # your name (or website title) here
logo: "/images/mugshot_round.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Philip Tuomey
  <br><br>
  Full Stack Blockchain EngineerğŸ”— | Solidity Developer ğŸ’» | Smart Contracts ğŸ¤ | DeFi ğŸ’° | NFT's ğŸ’
  <br><br>
  <a href="https://www.linkedin.com/in/philiptuomey/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
